Implementare sortare, flag-uri si corectare limit

diff --git a/mylast b/mylast
--- a/mylast
+++ b/mylast
@@ -7,14 +7,14 @@ USER_FILTER=""
 
 while [ $# -gt 0 ]; do
     case "$1" in
-	-n)
+        -n)
             LIMIT="$2"
-            [ -z "$LIMIT" ] && { echo "Limita invalida"; exit 1; }
+	    ! [ "$LIMIT" -eq "$LIMIT" ] 2>/dev/null && { echo "Limita invalida"; exit 1; }
             shift 2
             ;;
         -p)
             USER_FILTER="$2"
-            [ -z "$USER_FILTER" ] && { echo "User invalid"; exit 1; }
+	    [ -z "$USER_FILTER" ] && { echo "User invalid"; exit 1; }
             shift 2
             ;;
         -s)
@@ -42,6 +42,7 @@ read_logs() {
         fi
     done
 }
+
 read_logs | while read -r line; do
     is_login=false
     user=""
@@ -58,7 +59,23 @@ read_logs | while read -r line; do
 
     [ "$is_login" = false ] && continue
     [ "$user" = "gdm" ] && continue
+    [ -n "$USER_FILTER" ] && [ "$USER_FILTER" != "$user" ] && continue
 
     log_time=$(echo "$line" | awk '{print $1}')
-    echo "$user logged in at $log_time"
-done
+    line_epoch=$(date -d "$log_time" +%s 2>/dev/null)
+    [ -z "$line_epoch" ] && continue
+    [ -n "$START_EPOCH" ] && [ "$line_epoch" -lt "$START_EPOCH" ] && continue
+    [ -n "$END_EPOCH" ] && [ "$line_epoch" -gt "$END_EPOCH" ] && continue
+
+    echo "$line_epoch $user logged in at $log_time"
+done | sort -nr | {
+    count=0
+    while read -r line; do
+        if [ -n "$LIMIT" ]; then
+            count=$((count + 1))
+            [ "$count" -gt "$LIMIT" ] && break
+        fi
+        echo "$line" | cut -d' ' -f2-
+    done
+}
+
